KERNEL_SIZE: 100
image_size: [256, 256, 3]
primary_samples: 1000
backup_samples: 4000
num_epochs: 2000
densification_interval: 300
learning_rate: 0.01
image_file_name: "Image-01.png"
display_interval: 100
gradient_threshold: 0.002
gaussian_threshold: 0.002
display_loss: False
scale_reduction_factor: 1.6